before_install:
  - date
  - ./travis-ci/setup.sh
  - export PATH=`pwd`/sat/bin:$PATH
  - echo $PATH
  - export PATH=$HOME/.cabal/bin:$PATH
  - git clone https://github.com/ajhc/ajhc.git
  - cd ajhc && ./travis-ci/setup.sh && ./travis-ci/build.sh
  - cd $TRAVIS_BUILD_DIR && ./travis-ci/show_setting.sh
script:
  - cd $TRAVIS_BUILD_DIR
  - ./travis-ci/build.sh
after_script:
  - date
